services:
  web:
    image: node:20
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "npm run dev"

  api:
    image: golang:1.22.2
    environment:
      - AUTHORIZED_USERS=${AUTHORIZED_USERS}
      - SERVER_SECRET=${SERVER_SECRET}
      - ENCRYPTION_BCRYPT_COST=${ENCRYPTION_BCRYPT_COST}
    working_dir: /app
    volumes:
      - ./api:/app:ro
    command: bash -c "go mod download && go run cmd/main.go"

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
      - 3001:3001
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    command:
      - /bin/sh
      - -c
      - |
        set -e
        openssl req -newkey rsa:2048 -subj "/C=US/ST=Illinois/L=Chicago/O=Notes/CN=localhost" -nodes -keyout /tmp/localhost.key -x509 -days 365 -out /tmp/localhost.crt
        ls /tmp/
        nginx -g "daemon off;"
    depends_on:
      - web
      - api
