limit_req_zone $binary_remote_addr zone=authzone:10m rate=10r/s;

server { 
  listen              80;
  server_name         _;

  location /api/login {
    limit_req          zone=authzone burst=20;

    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass         http://127.0.0.1:8000/login;
    proxy_set_header   Host $http_host;
    proxy_cache_bypass $http_upgrade;
    proxy_redirect     off;
  }

  location /api/check {
    limit_req          zone=authzone burst=20;

    auth_request       /auth;

    try_files "" @auth_success;
  }

  location @auth_success {
    return 204;
  }

  location /api/ {
    limit_req          zone=authzone burst=20;

    auth_request       /auth;
    auth_request_set   $auth_status $upstream_status;

    # this gets called right after auth_request returns.
    # it reads http "authorization" header from upstream (= auth_request)
    # and sets it to the variable $auth_header
    # https://serverfault.com/a/950019/373603
    auth_request_set   $auth_header $upstream_http_authorization;

    proxy_set_header   Authorization "$auth_header";
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass         http://127.0.0.1:7700/;
    proxy_set_header   Host $http_host;
    proxy_cache_bypass $http_upgrade;
    proxy_redirect     off;
  }

  location = /auth {
    internal;
    proxy_pass              http://127.0.0.1:8000;
    proxy_pass_request_body off;
    proxy_set_header        Content-Length "";
    proxy_set_header        X-Original-URI $request_uri;
  }

  location / {
    root /var/www/html;
  }
}